language: ruby
sudo: false
dist: trusty
cache: bundler
before_install:
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"
  # https://github.com/rubygems/rubygems/issues/1448
  - gem update --system
  # I don't know why I need to install this on travis in order for tests to function.
  - gem install bundler samovar
rvm:
  - 2.2
  - 2.3
  - 2.4
  - jruby-head
  - ruby-head
env: COVERAGE=true BENCHMARK=true CC_TEST_REPORTER_ID=5ee699ecfc13ca99e60bc3ab134f16e8306c11a359ace1c9e906195995e93731
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
