language: ruby
dist: xenial
cache: bundler

before_install:
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"

script:
  - bundle exec rake test

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: COVERAGE=PartialSummary,Coveralls
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
